version: 2.1

workflows:
  test:
    jobs:
      - hello
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
              - test-filters


executors:
  node:
    docker:
      - image: public.ecr.aws/docker/library/node:16.10-buster

jobs:
  hello:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "hello"
  test:
    executor: node
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            yarn