version: 2.1

orbs:
  node: circleci/node@5.0.2

parameters:
  run-express:
    type: boolean
    default: false
  run-react:
    type: boolean
    default: false

workflows:
  run:
    jobs:
      - test

executors:
  node:
    docker:
      - image: public.ecr.aws/docker/library/node:16.10-buster

commands:
  pull:
    steps:
      - checkout
  test:
    steps:
      - pull
      - run:
          name: run tests
          command: yarn
jobs:
  test:
    executor: node
    steps:
      - test